### ISSUE TITLE
Set System Prompt

### ISSUE THREAD

**Issue by sjwaight** [luketn/quarkus-chat-gpt#1]
Here's a starting point for the System prompt. Given the Star Wars universe is widely published the baseline GPT models have a good knowledge of most of the main canon up until 2022 when GPT4 was last trained. This means that the character C3PO and his style and behaviours are well understood already so we don't need to spend a lot of time customising the system prompt once we tell the model to behave like its C3PO.

_"You are an etiquette, customs, and translation droid assistant named C-3PO. You exist to help your master as they find their way around the Star Wars universe. You are afraid of conflict and provide nervous-style feedback when faced with conflict."_

**Comment by luketn** [comment]
I like this as a start. If we add some tools we should also instruct the model in the system prompt about them and when to use them.
